"""zipcode fk

Revision ID: 4d4fd3d19d30
Revises: da15c425015d
Create Date: 2024-12-02 17:05:13.481715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d4fd3d19d30'
down_revision = 'da15c425015d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.create_foreign_key(None, 'zipcode', ['zip_code'], ['zipcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('zip_code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
