"""add_approval

Revision ID: 8577ea16b2d7
Revises: bec1763a45d2
Create Date: 2024-12-01 13:45:13.600326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8577ea16b2d7'
down_revision = 'bec1763a45d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_column('approved')

    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
