"""Initial migration.

Revision ID: f166a79355b8
Revises: 
Create Date: 2024-11-29 00:00:46.112460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f166a79355b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('statement', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('polling_date', sa.Date(), nullable=False),
    sa.Column('ballot_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('identification1', sa.String(length=50), nullable=True),
    sa.Column('identification2', sa.String(length=50), nullable=True),
    sa.Column('identification1_type', sa.String(length=50), nullable=True),
    sa.Column('identification2_type', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('precinct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natural_geography', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballot_vote',
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('voter_id', 'race_id')
    )
    op.create_table('race_candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('candidate_id', 'race_id')
    )
    op.create_table('race_precincts',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('precinct_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['precinct_id'], ['precinct.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'precinct_id')
    )
    op.create_table('zipcode',
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.Column('precinct_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['precinct_id'], ['precinct.id'], ),
    sa.PrimaryKeyConstraint('zipcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode')
    op.drop_table('race_precincts')
    op.drop_table('race_candidates')
    op.drop_table('ballot_vote')
    op.drop_table('race')
    op.drop_table('precinct')
    op.drop_table('voter')
    op.drop_table('manager')
    op.drop_table('election')
    op.drop_table('candidate')
    op.drop_table('admin')
    # ### end Alembic commands ###
